version: "3.8"
services:
  jekyll:
    build:
      context: .
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --force_polling -H 0.0.0.0 -P 4000
